#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-bacon-colored_output
Version  : 1.0.1
Release  : 1
URL      : https://rubygems.org/downloads/bacon-colored_output-1.0.1.gem
Source0  : https://rubygems.org/downloads/bacon-colored_output-1.0.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bacon
BuildRequires : rubygem-rdoc

%description
# Bacon::ColoredOutput
Make your test output more readable!
![Neat, isn't it?](http://i.imgur.com/EpTpw.png)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n bacon-colored_output-1.0.1
gem spec %{SOURCE0} -l --ruby > rubygem-bacon-colored_output.gemspec

%build
gem build rubygem-bacon-colored_output.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
bacon-colored_output-1.0.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/bacon-colored_output-1.0.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/bacon-colored_output-1.0.1/ri/Bacon/ColoredOutput/cdesc-ColoredOutput.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-colored_output-1.0.1/ri/Bacon/ColoredOutput/color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-colored_output-1.0.1/ri/Bacon/ColoredOutput/handle_requirement-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-colored_output-1.0.1/ri/Bacon/cdesc-Bacon.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-colored_output-1.0.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/bacon-colored_output-1.0.1/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/bacon-colored_output-1.0.1/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/bacon-colored_output-1.0.1/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/bacon-colored_output-1.0.1/README.md
/usr/lib64/ruby/gems/2.2.0/gems/bacon-colored_output-1.0.1/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/bacon-colored_output-1.0.1/bacon-colored_output.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/bacon-colored_output-1.0.1/lib/bacon/colored_output.rb
/usr/lib64/ruby/gems/2.2.0/specifications/bacon-colored_output-1.0.1.gemspec
